### ISSUE TITLE
Vorlage.tex --> Vorlage.cls

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#103]
Ich denke es ist langsam an der Zeit, das Ding erwachsen werden zu lassen und darauf eine Latex-Klasse zu machen :)

**Comment by jemand771** [comment]
versteh ich nicht aber mach mal xD was ändert sich dafür am einbinden der vorlage, build-prozess usw. ? :D

**Comment by DSczyrba** [comment]
nop tut es nicht

**Comment by TheColin21** [comment]
was genau ist eigentlich der vorteil daran? @DSczyrba

**Comment by DSczyrba** [comment]
Es wirkt professioneller :D

**Comment by TheColin21** [comment]
.... ja okay das schreit nach wontfix
