### ISSUE TITLE
erinnerung: latex-workshop in openvsx kaputt

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#112]
abwarten 😅

**Comment by DSczyrba** [comment]
Ist inzwischen wohl gefixt.

**Comment by jemand771** [comment]
eyyy chill mal xD

**Comment by DSczyrba** [comment]
Sollte doch jetzt erledigt sein finally :D

**Comment by jemand771** [comment]
nach #119 ja :)

**Comment by jemand771** [comment]
minimales missverständnis im titel, ist aber jetzt (endgültig) gelöst ^-^
