### ISSUE TITLE
Ein Minted Template in der vorlage.tex erstellen, um die Bedienung leichter zu machen.

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#115]
![image](https://user-images.githubusercontent.com/45792945/133968262-29e5d8a7-a9ea-48f9-9401-eaebbcb8764f.png)

Siehe dazu die minted Dokumentation http://tug.ctan.org/macros/latex/contrib/minted/minted.pdf
Ab Seite 29ff

**Comment by TheColin21** [comment]
Ansätze dazu in #121

**Comment by TheColin21** [comment]
reicht das schon? xD

**Comment by DSczyrba** [comment]
Ist jedenfalls ein guter Anfang...

**Comment by TheColin21** [comment]
was genau wöllten wir hiermit eigentlich noch weiter erreichen? ist mir nicht ganz klar

**Comment by TheColin21** [comment]
fixed by #121 in Release 2.1.0
