### ISSUE TITLE
Autoren-Liste in PDF-Metadatan dynamisch erzeugen

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#128]
```
\newcommand{\checkfor}[1]{%
  \ifcsname#1\endcsname%
    ... command '#1' exists ...%
  \else%
    ... command '#1' does not exist ...%
  \fi%
}
```

_Originally posted by @DSczyrba in https://github.com/DSczyrba/Vorlage-Latex/pull/127#discussion_r718474149_

**Comment by TheColin21** [comment]
hat nicht auf anhieb so funktioniert, wie ich dachte, darf @DSczyrba  machen

**Comment by DSczyrba** [comment]
Warum ich....

**Comment by TheColin21** [comment]
deine Idee

**Comment by jemand771** [comment]
ah, ich glaube das hat github beim kommentar zu issue konvertieren automatisch gemacht. ups ^^

**Comment by DSczyrba** [comment]
:D RIppi

**Comment by jemand771** [comment]
![image](https://user-images.githubusercontent.com/19669567/141126950-dd01d6ea-6e8b-4c5c-90ed-7ff2afed6b4f.png)
ja then fucking act like it
