### ISSUE TITLE
Automatische Großschreibung für Nachnamen ist meh.

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#138]
### Aktuelles Verhalten
commit d80d0f7328a2e8cc431e1014d56f4d53c0ecb1ec (merge: #123, release: [2.1](https://github.com/DSczyrba/Vorlage-Latex/releases/tag/2.1)) erzwingt die grosschreibung von nachnamen. das ist ganz nice, weil z.b.
```
@Online{SCZYRBA2020,
  author  = {Sczyrba, Dominic and Pohle, Colin and Hille, Willy},
  ...
}
```
gerendert wird als
![image](https://user-images.githubusercontent.com/19669567/139426629-e50b2109-b263-4594-88b7-34de6025ee6f.png)

### Problem
in seltenen fällen will man "nachnamen" nicht gross schreiben. das trifft vor allem zu, wenn man die "rohe" autoren-syntax benutzt: (nb: doppelte geschweifte klammern)
```
@Online{SCZYRBA2020,
  author  = {{SCZYRBA, Dominic; POHLE, Colin; HILLE, Willy}},
  ...
}
```
warum sollte man das wollen? z.b. für künstler- order firmennamen, die in in uppercase ihre "marke" verlieren oder einfach nur dumm aussehen. beispiel:
```
  author   = {{Intenta GmbH}}
```
rendert als
![image](https://user-images.githubusercontent.com/19669567/139426980-ddb3767f-1889-43a7-859e-928429848d19.png)
(hintergrund: der rohe name ist parameter `#1`, aka der "nachname" (vorname ist dann `#2` so wie's aussieht))

das ist imo richtig dämlich

### Lösung
die begrenzung auf 3 autoren würde ich drin lassen -> nicht den gesamten commit reverten.

entweder finden wir einen weg, nur das 1. argument gross zu schreiben, wenn es mehr als 1 argument gibt (und autoren mit nur einem namensfeld in ruhe zu lassen), oder wir nehmen das grosschreib-feature ganz raus.

was sagt ihr? :D

**Comment by TheColin21** [comment]
wenn ich so drüber nachdenk, ergibt dein beispiel mit der erklärung noch nich so wirklich sinn. Intenta GmbH wurde zu INTENTA GMBH, es wurde also beides als Nachname erkannt und groß geschrieben.

**Comment by TheColin21** [comment]
Anderer Ansatz: irgendwie LaTeX / Biber dazu bringen, nur zu makeuppercasen, wenn der Autor nicht in doppelten Klammern steht bzw. es irgendwie anders dazu zwingen, einen namen nicht anzufassen

**Comment by TheColin21** [comment]
ich finde nach längerem suchen keine wirkliche lösung. man müsste schaffen, dass das DeclareNameFormat Kommando nur greift, wenn das "author" feld nicht in {{}} steht. Ich weiß nur nicht, wie.

**Comment by TheColin21** [comment]
fixed by #139 goddammit.
