### ISSUE TITLE
quellenverzeichnis: et al ("u.a.") bei mehr als 3 autoren fehlt

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#145]
das ist quasi kaputt.

3 autoren:
`author = {Andreas Spillner and Thomas Roßner and Mario Winter},`
-->
![image](https://user-images.githubusercontent.com/19669567/140763865-e67c5b37-c587-4bad-9b0d-baf1d7fcbafa.png)
(gut)

4 autoren:
`author = {Andreas Spillner and Thomas Roßner and Mario Winter and Tilo Linz},`
-->
![image](https://user-images.githubusercontent.com/19669567/140763791-4e724064-a5ad-4166-9fcc-50b3fb4d1528.png)
(schlecht)

hawa sagt
![image](https://user-images.githubusercontent.com/19669567/140764330-2e36c05d-cde3-4cd7-bcf8-41d651a91d73.png)

**Comment by DSczyrba** [comment]
Klingt eindeutig nach einem Fall für @TheColin21 ...

Finde übrigens sehr schade, dass die BA nicht et al. nimmt :D

**Comment by TheColin21** [comment]
versteh ich das richtig, nicht nur in der Fußnote sondern auch im Quellenverzeichnis soll dann nur AUTOR Eins; u.a. stehen?

**Comment by jemand771** [comment]
irgendwie hab ich das gefühl, die PRs die issues automatisch schliessen gehen nicht mehr richtig 🤔
