### ISSUE TITLE
Anhangverzeichnis Formatierung

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#21]
## Korrektur Anhangverzeichnis

**Die Formatierung des Anhangsverzeichnis sollte man formal an die anderen Verzeichnis anpassen**

- Abstand

- Fett am Anfang

- Zeilenabstand

**Comment by TheColin21** [comment]
Sehr schöne Idee, entspricht aber nicht HWA

**Comment by DSczyrba** [comment]
Hab mit anderem dualen Studenten gesprochen, die sollten das Anpassen, weils ein Fehler in der HAWA bzw. egal ist.

**Comment by TheColin21** [comment]
hab da grade mal aus spaß rein geschaut, aber keine Ahnung, wie das funktioniert. Würde ich aber schon priorisieren, wenn das tatsächlich so sein soll.

**Comment by DSczyrba** [comment]
Würde ich übernehmen
