### ISSUE TITLE
Sonderzeichen in PDF-Meta

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#25]
in meiner `metadaten.sty` ist der `\titel` mit einem ü und einem \_ (muss man escapen weil nicht im math mode und so), im pdf-titel selbst kommt dabei nur Scheisse raus:
aus "für" wird "fu127 ur" und aus "rd\_stream" macht es "rdwidth.3emstream"

komisch: wenn ich (nach https://tex.stackexchange.com/a/12988/220899) einfach nur irgendwann nach dem `\usepackage[...]{hyperref}` ein `\hypersetup{pdftitle={\titel}}` einfüge - also genau den gleichen Titel setze wie vorher auch, dann geht's. Gleiches Problem mit dem subject und author in den pdf-metadaten.

Kann das jemand nachstellen, oder hab ich bei mir irgendwo trashy encoding eingestellt? Bsp: "äöü" als `\autoren`, `\titel` und `\kurzeschreibung` setzen -> kommt müll raus, dann die Änderung machen -> steht richtig "äöü" da.

also aus (momentan ab [zeile 80](https://github.com/DSczyrba/Vorlage-Latex/blob/d9e6c1cd806972cd418ed5aac52d31fccab0c81d/Latex/vorlage.tex#L80) auf dev)
```latex
\usepackage[
	hidelinks,
	pdftitle={\titel},
	pdfsubject={\kurzbeschreibung},
	pdfauthor={\autoren},
]{hyperref}
```
wird
```latex
\usepackage[hidelinks]{hyperref}
\hypersetup{pdftitle={\titel}}
\hypersetup{pdfsubject={\kurzbeschreibung}}
\hypersetup{pdfauthor={\autoren}}
```

(pdf-meta angeguckt habe ich mit `exiftool main.pdf`)

**Comment by DSczyrba** [comment]
Bitte ein vollständiges Minimalbeispiel liefern, dass das auch für jedermann nachvollziehbar ist 👍

**Comment by jemand771** [comment]
1. in `metadaten.sty`:
```latex
\newcommand{\autoren}{ü}
```
2. pdf bauen
3. `exiftool main.pdf`
```
ExifTool Version Number         : 11.16
File Name                       : main.pdf
[...]
Author                          : u127 u
[...]
```

**Comment by DSczyrba** [comment]
Bitte halte dich an die Regeln für ein [vollständiges Minimalbeispiel](https://golatex.de/wiki/index.php?title=Minimalbeispiel)...

**Comment by TheColin21** [comment]
@DSczyrba du entwickelst dich immer mehr zu Michael Kohm

**Comment by DSczyrba** [comment]
Ich troll nur :D

**Comment by jemand771** [comment]
ich dachte der TI-hass war spontan wieder da xD

**Comment by DSczyrba** [comment]
Du hast trotzdem kein vollständiges Minimalbeispiel gemacht :D
Aber ja kann schon sein, dass es nicht geht, aber das ist nichts womit man sich rumschlagen müsste glaube ich

**Comment by jemand771** [comment]
auf der seite die du verlinkt hast steht dass ich alle includes / inputs mit reinkopieren soll. aka die ganze vorlage ans issue anhängen weil ich ja "nicht weiss wie man das behebt"? lol

Naja, denkst du nicht dass Umlaute im Titel nicht ganz unwahrscheinlich sind? Wenn du das nicht im repo ändern willst kann ich das auch nur bei mir lokal lassen - ist ja egal wo die `\hypersetup`-zeilen hin kommen.

**Comment by DSczyrba** [comment]
machn request, dann änder ich es.
hab nur gerade keinen nerv, dass im dev ordner zu ändern.

**Comment by DSczyrba** [comment]
Scheint wohl doch noch nicht ganz zu funktionieren

**Comment by TheColin21** [comment]
Ich hab mir das grade mal angeschaut, der Fix den @jemand771  mal eingearbeitet hat, war einfach nicht mehr drin, da muss wahrscheinlich mal was beim hin und her mergen verloren gegangen sein, ich werd da gleich nochmal ne neue Anfrage stellen...

**Comment by jemand771** [comment]
hab's für den/die autor(en) nochmal ausprobiert, da werden sonderzeichen richtig übernommen. ich geh' davon aus bei den anderen feldern geht's auch wieder.
ich mach mal zu weil fixed in 243ae43349638c50f2d7c0d94c0ea3e0cbe1fa9f
