### ISSUE TITLE
Biblatex Style

### ISSUE THREAD

**Issue by ParkerSnable** [DSczyrba/Vorlage-Latex#27]
Als  Biblatex-Style könnte man Geschichtsfrkl verwenden, das sollte zu den Forderungen der BA passen.

**Comment by DSczyrba** [comment]
Soweit ich weiß hat @TheColin21 doch schon den Style nach unseren Vorgaben angepasst...

**Comment by TheColin21** [comment]
Hab ich, das wäre nur in der Standardkonfiguration schon näher dran und würde glaube auch die CAPS mit machen, wär aber halt nochmal Aufwand umzubauen

**Comment by DSczyrba** [comment]
Also was schlagt ihr vor?

**Comment by TheColin21** [comment]
Auf die todo setzen aber niedrig priorisieren

**Comment by DSczyrba** [comment]
[Naja der Zitierstil ist ja völlig übermüllt ;D](http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/biblatex-contrib/geschichtsfrkl/geschichtsfrkl.pdf)

Ich zitiere tagtäglich mittelalterliche Urkunden xd

**Comment by DSczyrba** [comment]
Muss jetzt hier eigentlich noch was gemacht werden @TheColin21 und @ParkerSnable ?

**Comment by TheColin21** [comment]
Ich sach ma so: kann man, muss man aber nicht

**Comment by TheColin21** [comment]
da wir genug anderes zu tun haben und ich eh nich denke, dass das jemals jemand umsetzt
