### ISSUE TITLE
UTF-8 Fehler

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#28]
```
{
	"resource": "/c:/Users/Dominic.Sczyrba/Desktop/Digitaltechnik/Latex/inhalt/Kapitel2.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Package inputenc: Unicode character   (U+2003)\n(inputenc)\tnot set up for use with LaTeX.\n",
	"source": "LaTeX",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 65536
}
```

![image](https://user-images.githubusercontent.com/45792945/89625086-8d451e80-d897-11ea-9d8c-3354d7c2730f.png)

Kann irgendwer helfen bzw. weiß woran es liegt?

**Comment by AlexPietz** [comment]
Du hast in Kapitel2.tex wahrscheinlich ein "em space" character:
http://www.fileformat.info/info/unicode/char/2003/index.htm

LaTeX weiss damit nichts anzufangen, du kannst also entweder:
- Den Character im Kapitel2 ersetzen (der oben verlinkte Link laesst dich den Char kopieren), oder
- Den Character explizit deklarieren; z.B. als \quad (1em breit). Minimales Beispiel:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\DeclareUnicodeCharacter{2003}{\quad}

\begin{document}
b a
%^em space
\end{document}
```
