### ISSUE TITLE
Fehler bei \nameref auf Anhänge

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#29]
Es ist im aktuellen Stand nicht möglich den Befehl `\nameref` auf einen Anhang anzuwenden...
Statt des Namens des Anhangs erscheint die letzte Überschrift.

Der normale Befehl `\ref` gibt die richtige Nummer aus.

**Comment by DSczyrba** [comment]
Was hatte ich damit gemeint? :D @TheColin21 @jemand771, weiß das wer?

**Comment by TheColin21** [comment]
Nich so direkt

Am 3. Dezember 2020 15:33:50 MEZ schrieb Chicken69 <notifications@github.com>:

**Comment by jemand771** [comment]
1. @TheColin21 ich wusste nicht dass irgendjemand tatsächlich die kommentar-antworten per email benutzt :D
2. @DSczyrba wir hatten glaube mal ein problem mit `\section`, `\subsection`, usw im anhang. ich glaube damals ging's drum, dass die überschriften labels bekommen soll damit man sie `\ref`en kann, oder so ähnlich

am anfang des anhangs wird ja der `\section` command umgeschrieben, damit der titel auf den folgenden anhangs-seiten oben in der kopfzeile steht statt einmalig als übschrift im text:
```tex
\renewcommand{\section}[1]{
\par\refstepcounter{section}
\sectionmark{#1}
\addcontentsline{atoc}{section}{\protect\numberline{\thesection}#1}
\lohead{\textnormal{#1}}
}
```
das ist doof, wenn man subsections (also ganz normale unter-übschriften während des anhangs) benutzen möchte. bsp:
```tex
\section{Erster toller Anhang}
Hihi hier kommt eigentlich ein Anhangverzeichnis hin :D
\subsection{shit}
\subsection{bla}
```
![image](https://user-images.githubusercontent.com/19669567/101359869-24010680-389d-11eb-9c2d-ee81941cfab4.png)

**Comment by DSczyrba** [comment]
Ja, du hast Recht, das führt natürlich zu Problemen... Allerdings (siehe HAWA), ist ein Untergliedern des Anhangs gar nicht gewünscht, bzw. soll möglich sein.

Ich denke als das kann man getrost so lassen.

Ich seh sonst keine Lösung, ohne eine Überschrift alias Section zu haben, und die auch anzuzeigen...

Allerdings funktioniert das \ref{anhangx} inzwischen auch aus irgendwelchen Gründen :D

**Comment by jemand771** [comment]
wenn das mittlerweile geht weiss ich auch nicht mehr was noch fehlen soll ^^

**Comment by TheColin21** [comment]
sieht ja so aus, als wäre hier nichts effektiv zu tun

**Comment by TheColin21** [comment]
> 
> 
> Das Problem ist nach wie vor bestehend. Allerdings nicht ganz so wie beschrieben...
> 
> Man kann im Textteil nicht auf einen bestimmten Anhang referenzieren.
> 
> Wenn ich `\section{Anhang 1}` und darunter `\label{sec:anhang1}` schreibe, lässt sich im Textteil nicht auf den Anhang referenzieren, per `\ref{sec:anhang1}`.
> Es erscheint nur ein Fragezeichen...

auch das scheint nicht korrekt zu sein. Als ich das versucht habe, per `\aref` auf Anhang 1: Erster toller Anhang zu verweisen, hat das funktioniert. Allerdings als "Anhang 1", nicht erster toller anhang.

**Comment by TheColin21** [comment]
> 
> 
> Hast du mal `\refname` probiert?

jetzt ja, das isses auch nich

**Comment by TheColin21** [comment]
ich denke, dadurch, wie wir unsere Anhänge behandeln wird ein verweisen darauf mit korrektem Name nicht wirklich gehen. mMn reicht sowas wie _siehe Anhang 2_ im Text aber auch aus. Gern schließen wegen mir

**Comment by jemand771** [comment]
ich fänd's schon praktisch wenn man auf teile eines langen anhangs verweisen könnte

**Comment by DSczyrba** [comment]
Wie meinst du teile eines langen Anhanges? 
Das könntest du ja höchstens realisieren mit 
_siehe Anhang 1 (Seite 3)_ der Anhang ist ja, bei mehrseitig, in sich nummeriert...

Wichtiger wäre es denk ich, dass anhänge direkt gehen... Also das man das ohne viel klimm bimm refbar machen kann.

**Comment by TheColin21** [comment]
Da das hier noch nicht explizit stand: \nameref auf Anhänge funktioniert nicht, das heißt, man kann den Titel eines Anhangs nicht referenziren, was für #134 bzw. #136 ein Problem darstellt

**Comment by DSczyrba** [comment]
Die Frage ist funktioniert `\ref`?
Ich weiß noch nicht ganz genau wo das Problem liegt, ich werde mir das dann mal anschauen, weil das nervt echt.

**Comment by DSczyrba** [comment]
Gut, dann können wir das aber so machen...
Beim Anhang wird man eh keinen der refs brauchen...

ich schätze mal (siehe Anhang 1) ist da ausreichend xd

**Comment by TheColin21** [comment]
Kann man machen, ist dann halt nicht einheitlich.

**Comment by TheColin21** [comment]
Wissen wir, wieso?

**Comment by TheColin21** [comment]
sobald Lösung gefunden, aref Kommandos wieder vereinheitlichen

**Comment by TheColin21** [comment]
https://tex.stackexchange.com/questions/622038/nameref-is-broken-after-renewing-sections-command
