### ISSUE TITLE
Fehlende Erklärung zur Prüfung auf Plagiate

### ISSUE THREAD

**Issue by TheColin21** [DSczyrba/Vorlage-Latex#38]
die Seite existiert noch nicht....

s. https://www.ba-glauchau.de/fileadmin/glauchau/waehrend-des-studium/dokumente/pruefungen/4BA-F.207_Hinweise_zur_Anfertigung_wissenschaftlicher_Arbeiten.pdf

Seite 39

**Comment by DSczyrba** [comment]
Glaube das muss nur an Bachelor / Diplomarbeit... Aber haben ist besser als hätten :D
