### ISSUE TITLE
Ausrichtung Captions für Code-Umgebung

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#40]
Eyo!
Die Caption für das `code`-environment ist zentriert und nicht linksbündig. das mag bei superlangen codezeilen besser aussehen, finde ich aber für die meissten anwendungen ungeeignet.

Beispiel mit aktueller vorlage aus 330c15ca9f1731f0b99253a3379d2ff503bb47e5:
```tex
\begin{code}
\inputminted[linenos, breaklines, gobble=0, frame=none,
        firstline=1,
        lastline=3,
        firstnumber=1,
        numbers=left,
        numbersep=5pt]{python}{test.py}
\caption{test-code}
\end{code}
```

Ergebnis:
![image](https://user-images.githubusercontent.com/19669567/100995654-5d154000-3558-11eb-8705-aee9426f73ed.png)
(die `aaaaa` oben for scale)

(Ich seh jetzt erst, dass die bildunterschrift vielleicht auch bisschen weit unten ist und die zeilennummern etwas nach links aus dem rand ragen, aber das kann täuschen.)

ist die caption allgemein mit absicht zentriert? ich komm leider nicht drauf wie ich die (evtl. nur lokal) nach links ziehen kann.

**Comment by jemand771** [comment]
beispiel, ohne dass man eine `test.py` braucht:
```tex
\begin{code}
\begin{minted}{python}
import shit
def stuff():
    yes = True
\end{minted}
\end{code}
```
gleiches ergebnis (nur ohne zeilennummern weil `linenos` nicht mit angegeben ist)
![image](https://user-images.githubusercontent.com/19669567/100996628-913d3080-3559-11eb-9d54-ccf115f21667.png)

**Comment by DSczyrba** [comment]
Ja puh, was soll ich sagen, ich benutz die aktuelle Version und es links :D

![image](https://user-images.githubusercontent.com/45792945/100996973-06106a80-355a-11eb-9aae-4afa13b388b7.png)

**Comment by DSczyrba** [comment]
Selbst mit deinem Test Code in einem neu gezogenen Clone auf aktuellem Stand tritt das PRoblem nicht auf:

![image](https://user-images.githubusercontent.com/45792945/100997881-1f65e680-355b-11eb-9b8c-089664d02975.png)

**Comment by TheColin21** [comment]
![grafik](https://user-images.githubusercontent.com/24256864/100998076-6227be80-355b-11eb-8e53-5d5870c55597.png)

wenn ich @jemand771 's bsp einfüge

**Comment by DSczyrba** [comment]
Ja @jemand771 hat in seinem Test vergessen eine `\caption` zu setzen...

Try:
```
\begin{code}
    \begin{minted}{python}
    import shit
    def stuff():
        yes = True
    \end{minted}
    \caption{YOhoho}
\end{code}
```

**Comment by TheColin21** [comment]
war mir dann auch grade aufgefallen xD mit caption:
![grafik](https://user-images.githubusercontent.com/24256864/100998400-c2b6fb80-355b-11eb-8fd4-7837a1a08f9e.png)

**Comment by TheColin21** [comment]
es liegt also schonmal nich an @jemand771

**Comment by jemand771** [comment]
das ist jetzt super awkward, aber.. frischer clone von master:
![image](https://user-images.githubusercontent.com/19669567/100998474-dbbfac80-355b-11eb-8bbf-918bb94a13e3.png)

(hatte das `\caption` vergessen mit hier her zu schreiben, das war aber da. ^^)

einzige änderung (ausser den codeblock einzufügen):
```tex
%vorlage%
\input{vorlage}
%Dokument-Anfang
\renewcommand{\MintedPygmentize}{D:/software/conda/envs/minted/Scripts/pygmentize}
\begin{document}
```
--> braucht man, wen pygmentize nicht im path ist

**Comment by DSczyrba** [comment]
Können wir das mal auf RocketChat verlagern? :D
