### ISSUE TITLE
Abkürzungsverzeichnis

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#43]
Im zweiten Beitrag hier wird eine Möglichkeit gezeigt das Abkürzungsverzeichnis in eine zweispaltige Tabelle zu bekommen. Sollten wir eventuell noch einbauen, um diesen HickHack mit der längsten Bezeichnung zu sparen, weil die ist echt Sackgang.

[https://golatex.de/viewtopic.php?f=7&t=17670](https://golatex.de/viewtopic.php?f=7&t=17670)

**Comment by TheColin21** [comment]
Schöne Idee aber ist ja nicht wirklich hickhack, das einmal die längste Abkürzung oben rein und fertig.

Am 11. Dezember 2020 12:08:33 MEZ schrieb Chicken69 <notifications@github.com>:

**Comment by DSczyrba** [comment]
Die Umsetzung ist allerdings auch nicht wirklich schwer, insofern würde ich das schon so machen, zumal man sich dann an die Abstände aus den Verzeichnissen anpassen kann.

Wäre vielleicht ganz sexy

**Comment by TheColin21** [comment]
ich hab den Link gelesen, ich seh nich genau wo da geschrieben wird wie das gehen soll, hab in #56 das Beispiel bisschen erweitert, ich denke das reicht so. wenn du das auch so siehst @DSczyrba , dann bitte schließen

**Comment by jemand771** [comment]
@TheColin21 daddy chill

**Comment by DSczyrba** [comment]
Geht auch nicht so, hat sich also erledigt :D
