### ISSUE TITLE
Floats im Anhang landen eventuell auf der falschen Seite (z.B. im nächsten Anhang)

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#46]
Aktuell haben wir in der Standard-`Anhang.tex` dieses Beispiel:

```tex
%! Anhang 1
\section{Erster toller Anhang}
Hihi hier kommt eigentlich ein Anhangverzeichnis hin :D
\newpage

%! Anhang 2
\section{Inhalt der CD}
CD mit folgenden Inhalten:
\begin{itemize}
	\item dieses Dokument
	\item Latex Dateien
	\item Youtube-Video als Bonus
\end{itemize}
 \newpage
```

Dort sollten wir `\clearpage` statt `\newpage` verwenden, weil `\newpage` es floats wie Tabellen erlaubt, drüber raus zu rutschen. Nur damit da in Zukunft niemand rein rennt, bei mir ist nämlich gerade eine Tabelle aus Anhang 1 in Anhang 2 aufgetaucht, weil dazwischen nur ein `\newpage` stand.

Bei der Gelegenheit könnte man das `\clearpage` wahrscheinlich auch einfach in die `\section`-Redefinition hängen. Das ist aber optional.

@DSczyrba wird sich bestimmt wieder drüber aufregen dass ich keine Minimalbeispiele bring, aber ihr wisst ja was gemeint ist :D

**Comment by DSczyrba** [comment]
Wo ist das beschissene Minimalbeispiel?

**Comment by DSczyrba** [comment]
![image](https://user-images.githubusercontent.com/45792945/103793846-6bb5b200-5044-11eb-89fd-e601666beed0.png)
Ist das eigentlich noch ein Thema?

**Comment by DSczyrba** [comment]
Ja die Änderungen können wir auf jedenfall machen, sollte kein Problem darstellen.
