### ISSUE TITLE
README aufräumen und wiki

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#48]
das issue ist erstmal nur als platzhalter / notiz da, möglicherweise kann man das in mehrere kleinere aufgaben teilen ^^

- [x] changelog raus aus der readme -> wiki oder releases
- [ ] detailierte anleitung aus readme -> wiki
- [x] quickstart in die readme
- [x] evtl. mehr anleitungen/empfehlungen -> wiki (z.b. empfehlung jabref, setup texmaker, setup docker, ...)
- [x] liste aller "unserer" befehle als einfache referenz?

**Comment by jemand771** [comment]
hab https://github.com/DSczyrba/Vorlage-Latex/wiki/Installation-&-Einrichtung für meine git-strategie angepasst.
gibt konflikte, wenn wir sowas wie `\section` zu `\kapitel` umbenennen würden und das in den KapitelX.tex anpassen würden. machen wir ja aber _theoretisch_ irgendwann nicht mehr (und falls doch sind die konflikte von leuten die git können einfach zu lösen)

**Comment by DSczyrba** [comment]
Sollten wir solche Umbenennungen tun?
Sieht jedenfalls super aus!

**Comment by jemand771** [comment]
grundsätzlich nicht, geht nur drum wenn wir den einen oder anderen neuen befehl hinzufügen und die beispiel-dateien hier als test benutzen (jeden befehl irgendwo mindestens 1x verwenden, um per auto-build zu gucken, ob alles geht)

kommt ja aber nicht oft vor, weil wir ja in zukunft wahrscheinlich seltener releasen werden ^^

**Comment by DSczyrba** [comment]
Ich denke auch, die Frage ist nur, was alles einem Rewrite / Optimierungen zum Opfer fällt

**Comment by jemand771** [comment]
- [ ] git-setup-wiki up abschnitt über template repositories erweitern

**Comment by jemand771** [comment]
wenn wir die vorlage "erstmal fertig" (v2) nennen wollen und das einsteigerfreundlich sein soll (der sinn der ganzen QoL änderungen), sollten wir bis dahin auch anleitungen für alles wichtige haben ^^
(wenigstens ganz kurze bzw. links zu entsprechenden anleitungen)

**Comment by DSczyrba** [comment]
Die Frage ist wie viel wollen wir überhaupt ins Wiki packen, wenn die Vorlage sich quasi selbst dokumentieren soll?

Weil für mich gehört dann quasi alles in die Vorlage.pdf und nicht ins Wiki.?

**Comment by jemand771** [comment]
naja, ich würde sagen, alles was nicht LaTeX ist: git, vscode, container, gha, usw. bei sowas wie die dynamischen titelseiten (wenn es sie gibt) und automatisches laden von KapitelN.tex bin ich mir nicht sicher, das ist in der vorlage selbst evtl. auch schwierig komplett zu zeigen

**Comment by DSczyrba** [comment]
Man könnte aber auch gerade alles in der Arbeit dokumentieren inklusive git, vscode, gha etc.
Da hätte man die einsteigerfreundlichste Dokumentation der Vorlage überhaupt.

**Comment by jemand771** [comment]
gute idee. machen wir so, ich weiss aber nicht, wann ich damit anfang ^^
willst du das einfach direkt auf dev machen oder eher dev-beleg targeten?

**Comment by DSczyrba** [comment]
Eher dev-beleg als Ziel....
Wir sollten eventuell auch noch überlegen, wie wir das dann in die Vorlage packen...
Vielleicht alles in eine und sample.tex mitliefern oder gar nicht und nur die doku.pdf beilegen oder w/e...

Müssen wir uns noch überlegen...

**Comment by TheColin21** [comment]
letzter fehlender Punkt wird in #130 umgesetzt
