### ISSUE TITLE
Erweitern von Titelseiten und Erklärungen für n Autoren

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#50]
Bisher unterstützen wir 1-Autor-Belege (Anwendungsfall Praxisbeleg) und 3-Autor-Belege (Anwendung Gruppen-Projekte)

Geil wäre es natürlich, wenn man in `metadaten.sty` einstellen könnte, wie viele leute man ist, und dann auch sinnvolle namen für die befehle hat (weil das `\autoreins` `\autorzwei` `\autordrei` geht mir sowieso auf den sack).
Je nachdem wie viele Leute es sind wird dann automatisch ein sinnvolles Format gewählt (z.B. Adresse des Autors nur übernehmen, wenn es genau einen Autor gibt)
Das könnte man evtl. auch auf die Gutachter erweitern, mal sehen wie das passt.
Schön: weniger doppelten code und kein hin- und herwechseln von `\input`s mehr beim ersten setup

Hier zu tun:
- [ ] befehle in titelseite und erklärungen anpassen
- [x] rausfinden, wie man am besten loopen kann (python in latex oder irgendwie nativ)
- [ ] die erklärungen sprachlich+stilistisch anpassen (z.b. "wir"/"ich"; tabelle 90° drehen)
- [ ] sinnvolle entscheidungen treffen (z.b. max. anzahl an autoren testen, ab der alles auseinanderfällt)

kann ich gerne auch selber machen wenn ihr davon nicht begeistert seid, das bekomm' ich bestimmt hin. stell mir das mega geil vor :D

**Comment by TheColin21** [comment]
Schöne Idee, hau rsus😅

Am 8. Januar 2021 14:34:49 MEZ schrieb Willy <notifications@github.com>:

**Comment by DSczyrba** [comment]
Wenn wir python nehmen muss dann zwingend auch python im pfad liegen. Gut muss es ja wegen pygmentize sowieso.
Aber nur so als Hinweis. Aber prinzipiell fände ich das auch ganz geil :D

**Comment by jemand771** [comment]
note to self: `pythontex` findet man im debian-paket `texlive-extra-utils`. das fehlt derzeit im `:latest` container noch, in `:experimental` hab ich's schon drin (der command output ist noch bisschen suboptimal geregelt)

**Comment by jemand771** [comment]
@DSczyrba: ich hab mit @TheColin21 schon drüber diskutiert, in welche richtung soll die vorlage denn so allgemein gehen? unterstützen wir offiziell irgendwann nur noch den container build, oder soll das auch ohne gehen?

colin meinte, für das issue hier wäre es gut, die änderungen optional zu machen (wenn jemand kein python/pythontex hat) - das ist für kompatiblität gut, aber irgendwie auch extra-aufwand

**Comment by TheColin21** [comment]
laut @jemand771 den extrem hohen Aufwand absolut nicht wert, Version für 2 Autoren --> #152
