### ISSUE TITLE
Light-Version Entwickeln

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#51]
Entwicklung einer Light-Version
Ohne jegliche Verzeichnisse allerdings mit der selben Formatierung, um mal Fix ein Paper schreiben zu können.

Bin mir nur nicht sicher, wie sich das sinnvoll im Repo integrieren lässt.

**Comment by TheColin21** [comment]
Klingt gut. Würde sagen fork, alles außer main.tex und Vorlage.tex löschen und falls nötig dinge aus anderen Dateien (bspw. Kapitel.tex) in main.tex holen. Sollte sich dann eigentlich mit Vorlagen Updates hochziehen lassen denk ich.

Am 20. Januar 2021 19:44:07 MEZ schrieb Chicken69 <notifications@github.com>:

**Comment by jemand771** [comment]
überseh' ich jetzt was oder wäre die light-version einfach nur alle `\listofbla` commands auskommentieren und fertig? 😅 könnte man auch als einen befehl machen oder so. quasi "wenn \lite in metadaten.sty definiert ist, dann mal nicht verzeichnisse einfügen"

die metadaten.sty ist ja eh für jedes projekt verschieden (z.b. weil titel), von daher gibt das keinen extra-aufwand beim schreiben

**Comment by DSczyrba** [comment]
Die Metadata müsste aus der Light Version raus. Dann brauchst du nicht mehr die Ordnerstruktur...
Dann könnte man alle Bibliographie Sachen rausnehmen. Den ganzen \appendix scheiß raus.

Die Light Version ist schon eine massive Veränderung.

**Comment by TheColin21** [comment]
Is das nich quasi gemacht?

**Comment by DSczyrba** [comment]
Man könnte auch das ganze zu einem Projekt machen, mit Repos für Light / Full

**Comment by jemand771** [comment]
ist von daher blöd, dass sich dinge wie tasks.json, build-skripte, usw. dann doppeln würden - das wäre quasi schlimmer als jetzt

**Comment by DSczyrba** [comment]
Ist als vorlage_light.tex für fortgeschrittene Nutzer erstmal im Repo
