### ISSUE TITLE
Standard-Dateien für vscode (+evtl. andere Editoren?)

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#55]
Es wäre schlau+hilfreich, Dateien wie `.vscode/tasks.json` einmalig mit einzuchecken. Damit wird es noch einfacher, ein neues Dokument zu erstellen, weil alles, was man braucht, schon da ist. Die beste konfiguration für alle zu finden braucht evtl. ein paar Iterationen

An der Stelle bietet es sich auch an, Platz für eigene erweiterungen zu schaffen. Bsp: eine `post-build.sh`, in der man irgendwas automatisch machen lassen kann (nutzt z.b. colin wenn er auf seinem server arbeitet)
Die datei würde ich nicht mit ins repo packen und ignorieren, solange sie nicht exisitert

- [x] umgebung klären
- [x] build-skript(e)
- [x] tasks.json für vscode
- [ ] .idea/-ordner für jetbrains (kann man da analog build configurations anlegen ?)

ist als sub-issue von #47 zu sehen, dort passiert aber irgendwie zu viel ^^

**Comment by jemand771** [comment]
@DSczyrba, @TheColin21: können wir davon ausgehen dass jeder auf irgendeiner form von linux arbeitet? d.h. entweder wsl-remote in vscode, irgendeine andere linux-remote, direkt auf einem linux host, ... - das würde einigen denk-aufwand ersparen.

wenn man docker auf windows hat, hat man ja eigentlich sowieso wsl. und wenn man nicht per container baut: 1. warum nicht? :D 2. die build skripte/tasks.json/... interessieren einen dann eh nicht

**Comment by TheColin21** [comment]
ja können wir behaupte ich mal, wenn jemand texmaker nimmt is das dann eh egal

**Comment by DSczyrba** [comment]
> @DSczyrba, @TheColin21: können wir davon ausgehen dass jeder auf irgendeiner form von linux arbeitet? d.h. entweder wsl-remote in vscode, irgendeine andere linux-remote, direkt auf einem linux host, ... - das würde einigen denk-aufwand ersparen.
> 
> wenn man docker auf windows hat, hat man ja eigentlich sowieso wsl. und wenn man nicht per container baut: 1. warum nicht? :D 2. die build skripte/tasks.json/... interessieren einen dann eh nicht

Nein können wir nicht und möchte ich auch nicht :)

**Comment by jemand771** [comment]
build-skripte fallen insofern weg, dass wir mit #60 noch ein paar schöne tasks angelegt haben. wenn jemand was daran umstellen will (z.b. um mit texmaker zu arbeiten), muss er sowieso alles davon über den haufen schmeissen -> macht keinen sinn.

@TheColin21 für dich könnte an der stelle wahrscheinlich `dependsOn` und `dependsOrder` ganz interessant sein, wenn du wieder was mit nextcloud/occ tun willst:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "colin's shit",
            "dependsOrder": "sequence",
            "dependsOn": [
                "Build LaTeX using Docker",
                "colin's custom nextcloudcloud dings"
            ]
        },
        {
            "label": "colin's custom nextcloud dings",
            .....
        },
        .....
    ]
}
```

**Comment by TheColin21** [comment]
> 
> 
> build-skripte fallen insofern weg, dass wir mit #60 noch ein paar schöne tasks angelegt haben. wenn jemand was daran umstellen will (z.b. um mit texmaker zu arbeiten), muss er sowieso alles davon über den haufen schmeissen -> macht keinen sinn.
> 
> @TheColin21 für dich könnte an der stelle wahrscheinlich `dependsOn` und `dependsOrder` ganz interessant sein, wenn du wieder was mit nextcloud/occ tun willst:
> 
> ```json
> {
>     "version": "2.0.0",
>     "tasks": [
>         {
>             "label": "colin's shit",
>             "dependsOrder": "sequence",
>             "dependsOn": [
>                 "Build LaTeX using Docker",
>                 "colin's custom nextcloudcloud dings"
>             ]
>         },
>         {
>             "label": "colin's custom nextcloud dings",
>             .....
>         },
>         .....
>     ]
> }
> ```

das sieht tatsächlich interessant aus, mal schauen inwiefern es sinnvoller ist, als das aktuelle

**Comment by DSczyrba** [comment]
Ok, das hat sich inzwischen in eine ganz gute Richtung entwickelt...
Ist auf jeden Fall sehr benutzerfreundlich...

Aber jeden Editor werden wir durch Standarddateien auch nicht abdecken können.

**Comment by jemand771** [comment]
also, vscode als empfohlenen editor bezeichnen und nix weiter explizit unterstützen?
wäre auch nervig, wenn man das immer an 3 stellen ändern müsste ^^

**Comment by TheColin21** [comment]
jo würde VS Code empfehlen

**Comment by jemand771** [comment]
hast du ja in https://github.com/DSczyrba/Vorlage-Latex/commit/d015c2517d466c1957d6eff6f350cf0c2fda3cc9 schon geschrieben, easy :D
