### ISSUE TITLE
globale schalter/optionen

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#58]
colin hatte die idee, irgendwo einen bereich mit allgemeinen optionen anzulegen. dort könnte man z.b. die verwendung von pythontex (#50) an- und ausschalten oder sämtliche logos zwischen png und svg umstellen.

am coolsten fände ich persönlich, das ganze zu automatisieren (wenn inkscape gefunden -> svg verwenden), das ist aber wahrscheinlich keine gute idee

die optionen könnte man in der main.pdf (bevor die vorlage included wird) jeweils als `\newcommand` anlegen.
z.B. `\ENABLE_SVG` ist entweder `TRUE` oder `FALSE`

**Comment by TheColin21** [comment]
Ich hätte es halt so gemacht, dass standardmäßig die kompatiblere aber beschissenere Version an ist (png zB), aber dabei ne fette, schwer zu überstehende Meldung irgendwohin schreibt, die den Nutzer auffordert, sich das genauer anzusehen. Bei den Switches hätte ich dann jeweils was geschrieben à la "so wies jz isses geht zwar, aber is halt scheiße. Mach mal das hübsche da, das geht so: {...} Aber falls das für dich nich geht (weil zB keine Möglichkeit den Container zu nutzen), dann kannste hier die Warnung ausschalten"

Am 12. Mai 2021 10:16:53 MESZ schrieb Willy ***@***.***>:

**Comment by DSczyrba** [comment]
Automatisieren halte ich für Schwachsinn. Das heißt immer man bevormundet den Nutzer.

Ich bin allerdings sehr dafür diese globalen Optionen einzuführen.
Problem ist soweit ich weiß, dass man das in nem Erweiterungspaket machen muss oder in der main.tex deklarieren, sonst haben diese Command deklarationen durchaus Probleme, soweit ich das in Erinnerung habe.

**Comment by DSczyrba** [comment]
Bei der scheiße bin ich raus.

**Comment by TheColin21** [comment]
Klingt nach workflow verbesserung @jemand771

**Comment by jemand771** [comment]
neuer punkt hierfür: inhalt/KapitelN.tex automatisch laden lassen via pythontex

**Comment by DSczyrba** [comment]
Ist PythonTeX automatisch im Build Container aktiviert?

**Comment by jemand771** [comment]
@DSczyrba yup, ist by default an, dauert auch gar nicht lange. siehe auch https://github.com/jemand771/latex-build#environment-variables ^^

**Comment by DSczyrba** [comment]
Wird schwieriger als ich dachte...

**Comment by TheColin21** [comment]
laut @jemand771  nicht notwendig  bzw. viel zu viel Aufwand für zu wenig Nutzen
