### ISSUE TITLE
Latex Run und minted

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#70]
`inhalt/Kapitel3.tex:11: warning: Citation 'AZDELIVERY2021' on page 8 undefined
inhalt/Kapitel3.tex:107: error: [minted] Missing Pygments output; \inputminted was
      at ...   numbersep=5pt]{arduino}{code/main.cpp}
inhalt/Kapitel3.tex:125: error: [minted] Missing Pygments output; \inputminted was
      at       numbersep=5pt]{arduino}{code/main.cpp}`

Glaube da müssen wir uns noch was einfallen lassen...

**Comment by jemand771** [comment]
build-kontext? (docker/texmaker)
ich bin mir ziemlich sicher dass das schonmal ging. irgendwann

**Comment by DSczyrba** [comment]
Hab dich zu meinem privaten repo hinzugefügt...
Dort tritt der Fehler auf...

Ich kann morgen aber auch mal ein MWE erstellen dafür.

**Comment by jemand771** [comment]
update: liegt an minted's `autogobble`-option. reproducer:

* neue datei `Latex/code.py` erstellen. die kann leer sein und es tritt trotzdem der gleiche fehler auf
* irgendwo in den beispiel-dateien der vorlage das hier einfügen:
```tex
\inputminted[autogobble]{python}{code.py}
```
--> build schlägt fehl

* im gegensatz dazu
```tex
\inputminted[autogobble]{python}{code.py}
```
--> geht

getestet im docker-container, v1.0.0

warum das nicht geht? es bleibt spannend ^^

**Comment by DSczyrba** [comment]
Du hast dich glaub ich bei deinem Beispiel verschrieben :D
Da steht zweimal das gleiche... ICh schätze du meinstest beim zweiten ohne autogobble? :D

**Comment by jemand771** [comment]
durch 300% glück hab ich die lösung gefunden: minted will `/usr/bin/python`, im container gibt's aber nur `/usr/bin/pyton3`

gefunden hier:
https://github.com/alexpovel/latex-extras-docker/blob/5429a82ef415c2e9eda0c20f71e7df63b51621e9/Dockerfile#L80-L87

```dockerfile
# It is invoked with `python -c`, but Debian only has `python3`. Therefore, alias
# `python` to invoke `python3`. Use `update-alternatives` because it's cooler than
# symbolic linking, and made for this purpose.
# If `python` is not available but `pygmentize` is, stuff like `autogobble` and
# `\inputminted`won't work but syntax highlighting will.
# See also https://stackoverflow.com/a/55351449/11477374
# Last argument is `priority`, whose value shouldn't matter since there's nothing else.
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
```
