### ISSUE TITLE
diff-pdf

### ISSUE THREAD

**Issue by DSczyrba** [DSczyrba/Vorlage-Latex#71]
Hey @jemand771 wäre es eventuell möglich, in den Build Container dieses von dir besagte Diff-PDF mit einzubauen...
Und automatisch bei jedem Build eine Diff.pdf zu erzeugen... Ich fände das super praktisch.

**Comment by jemand771** [comment]
junge xD
seh' ich mir mit an ^^

**Comment by jemand771** [comment]
notiz zum testen: diff-erzeugung sollte standardmässig aus sein. ist sonst blöd wegen müll-dateien und unnötiger compilezeit

das komprimierte image geht damit von ~250mb auf ~300mb (2mb diff-pdf selbst, der rest dependencies wie xvfb). ist schon multi-stage, d.h. kleiner wird's nicht. ist denke ich verschmerzbar. entpackt liegt das dann irgendwo bei nem gigabyte (war ~800mb). das ist ein ganz schönes bisschen, aber auch nicht wirklich wild - finde ich

![image](https://user-images.githubusercontent.com/19669567/127902110-531e09d1-0c31-461e-ab16-351616c214ef.png)

jedenfalls wäre es umständlicher, ein eigenes diff-image sinnvoll in den workflow zu integrieren als das einfach teil des build-image zu machen

**Comment by TheColin21** [comment]
Die 50mb sind irrelevant denke ich 

Am 2. August 2021 19:41:18 MESZ schrieb Willy ***@***.***>:
