### ISSUE TITLE
line endings überprüfen

### ISSUE THREAD

**Issue by jemand771** [DSczyrba/Vorlage-Latex#98]
irgendwas stimmt hier nicht xD

**Comment by DSczyrba** [comment]
Wo?

**Comment by jemand771** [comment]
weiss nicht genau, wir hatten nur immermal merges bei denen eine zeile gelöscht und hinzugefügt werden, die identisch aussehen. das beispiel was mich daran erinnert hat war gar nicht so ein fall, deshalb hab ich das wieder rausgenommen

**Comment by jemand771** [comment]
angeblich ist alles ausser `Latex/bilder/ba_glauchau_logo.svg` LF, die svg ist CRLF. komisch, dass wir bei einigen commits so weirde
```
+ identische zeile
- identische zeile
```
diffs hatten. naja w/e

ihr könntet theoretisch `core.autocrlf=true` setzen, dann werden line endings beim commiten automatisch in LF umgewandelt. brauchen wir aber nicht wirklich, weil vscode sich ja an bestehende endungen einer datei hält. insofern wir also keine neuen dateien erstellen gibts hier nix zu tun. bei neuen dateien drauf achten, dass sie LF benutzen (wegen consistency)
